=== zorglub01/ProjectManager/ProjectManager/src/com/services/projects/model/Profile.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/Profile"
	xmlns:tns="http://www.example.org/Profile"
	elementFormDefault="qualified" xmlns:pref="http://www.example.org/PMOTask">

	<element name="Profile">
	<complexType>
		<choice>
		<sequence>
			<element name="Resources" type="tns:resource" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="Description" type="string"></element>
		</sequence>
		</choice>
		<attribute name="KeyId" type="string"></attribute>
		<attribute name="Name" type="string"></attribute>
	</complexType>
	</element>


	<complexType name="profileURI">
		<choice>
			<sequence>
				<element name="Credentials" type="tns:credentials"
					maxOccurs="1" minOccurs="1">
				</element>
				<element name="Path" type="string" maxOccurs="1"
					minOccurs="1">
				</element>
				<element name="Description" type="string"></element>
			</sequence>
		</choice>
	</complexType>

	
    <simpleType name="right">
    	<restriction base="string">
    		<enumeration value="CREATE"></enumeration>
    		<enumeration value="READ"></enumeration>
    		<enumeration value="UPDATE"></enumeration>
    		<enumeration value="DELETE"></enumeration>
    	</restriction>
    </simpleType>

    <complexType name="credentials">
    	<sequence>
    		<element name="rights" type="tns:right" maxOccurs="4" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="resource">
    	<sequence>
    		<element name="resource" type="tns:profileURI" maxOccurs="unbounded" minOccurs="1"></element>
    	</sequence>
    </complexType>

    <element name="User" >
    <complexType>
		<choice>
		<sequence>
			<element name="eMail" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="password" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element name="FirstName" type="string" maxOccurs="1"
				minOccurs="1">
			</element>
			<element ref="tns:Profile" maxOccurs="unbounded" minOccurs="1"></element>
		</sequence>
		</choice>
		<attribute name="KeyId" type="string"></attribute>
		<attribute name="login" type="string"></attribute>
	</complexType>
    </element>
</schema>

=== zorglub01/ProjectManager/ProjectManager/WebContent/DB/users/user_Admin.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:User KeyId="Admin" login="Admin" xmlns:tns="http://www.example.org/Profile"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Profile Profile.xsd ">
	<tns:eMail><![CDATA[Admin@mail.com]]></tns:eMail>
	<tns:password><![CDATA[MyPwd]]></tns:password>
	<tns:FirstName>Admin</tns:FirstName>
	<tns:Profile KeyId="1" Name="Admin" >
	<tns:Resources>
    <tns:resource>
      <tns:Credentials>
        <tns:rights>CREATE</tns:rights>
        <tns:rights>READ</tns:rights>
        <tns:rights>UPDATE</tns:rights>
        <tns:rights>DELETE</tns:rights>
      </tns:Credentials>      
      <tns:Path>/ProjectManager/admin/credAdmin.faces</tns:Path>
      <tns:Description>Admin page</tns:Description>
    </tns:resource>
    <tns:resource>
      <tns:Credentials>
        <tns:rights>CREATE</tns:rights>
        <tns:rights>READ</tns:rights>
        <tns:rights>UPDATE</tns:rights>
        <tns:rights>DELETE</tns:rights>
      </tns:Credentials>      
      <tns:Path>/ProjectManager/project/projectAdmin.faces</tns:Path>
      <tns:Description>Project page</tns:Description>
    </tns:resource>
    <tns:resource>
      <tns:Credentials>
        <tns:rights>CREATE</tns:rights>
        <tns:rights>READ</tns:rights>
        <tns:rights>UPDATE</tns:rights>
        <tns:rights>DELETE</tns:rights>
      </tns:Credentials>      
      <tns:Path>/ProjectManager/sample1/sample.html</tns:Path>
      <tns:Description>Project page</tns:Description>
    </tns:resource>
  </tns:Resources>
  <tns:Description>Admin profile setup</tns:Description>
</tns:Profile>
	</tns:User>

=== zorglub01/ProjectManager/ProjectManager/src/com/services/projects/model/Profile.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Profile KeyId="1" Name="Admin" xmlns:tns="http://www.example.org/Profile" xmlns:tns1="http://www.example.org/PMOTask" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Profile Profile.xsd ">
  
  <tns:Resources>
    <tns:resource>
      <tns:Credentials>
        <tns:rights>CREATE</tns:rights>
        <tns:rights>READ</tns:rights>
        <tns:rights>UPDATE</tns:rights>
        <tns:rights>DELETE</tns:rights>
      </tns:Credentials>      
      <tns:Path>admin/credAdmin.faces</tns:Path>
      <tns:Description>Admin page</tns:Description>
    </tns:resource>
    <tns:resource>
      <tns:Credentials>
        <tns:rights>CREATE</tns:rights>
        <tns:rights>READ</tns:rights>
        <tns:rights>UPDATE</tns:rights>
        <tns:rights>DELETE</tns:rights>
      </tns:Credentials>      
      <tns:Path>credPM.faces</tns:Path>
      <tns:Description>Project page</tns:Description>
    </tns:resource>
  </tns:Resources>
  <tns:Description>tns1:Description</tns:Description>
</tns:Profile>

=== zorglub01/ProjectManager/ProjectManager/WebContent/DB/profiles/profile_Admin.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Profile KeyId="1" Name="Admin" xmlns:tns="http://www.example.org/Profile" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Profile ../../projects/model/Profile.xsd ">
	<tns:Resources>
    <tns:resource>
      <tns:Credentials>
        <tns:rights>CREATE</tns:rights>
        <tns:rights>READ</tns:rights>
        <tns:rights>UPDATE</tns:rights>
        <tns:rights>DELETE</tns:rights>
      </tns:Credentials>      
      <tns:Path>/ProjectManager/admin/credAdmin.faces</tns:Path>
      <tns:Description>Admin page</tns:Description>
    </tns:resource>
    <tns:resource>
      <tns:Credentials>
        <tns:rights>CREATE</tns:rights>
        <tns:rights>READ</tns:rights>
        <tns:rights>UPDATE</tns:rights>
        <tns:rights>DELETE</tns:rights>
      </tns:Credentials>      
      <tns:Path>/ProjectManager/project/projectAdmin.faces</tns:Path>
      <tns:Description>Project page</tns:Description>
    </tns:resource>
    <tns:resource>
      <tns:Credentials>
        <tns:rights>CREATE</tns:rights>
        <tns:rights>READ</tns:rights>
        <tns:rights>UPDATE</tns:rights>
        <tns:rights>DELETE</tns:rights>
      </tns:Credentials>      
      <tns:Path>/ProjectManager/sample1/sample.html</tns:Path>
      <tns:Description>Project page</tns:Description>
    </tns:resource>
  </tns:Resources>
  <tns:Description>Admin profile setup</tns:Description>
</tns:Profile>

=== zorglub01/ProjectManager/ProjectManager/src/com/services/projects/model/Profile2.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Profile KeyId="" Name="" xmlns:tns="http://www.example.org/Profile" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Profile Profile.xsd ">
  
  <tns:Resources>
    <tns:resource>
      <tns:Credentials>
        <tns:rights>CREATE</tns:rights>
      </tns:Credentials>
      <tns:Path>tns:Path</tns:Path>
      <tns:Description>tns:Description</tns:Description>
    </tns:resource>
  </tns:Resources>
  <tns:Description>tns:Description</tns:Description>
</tns:Profile>

=== zorglub01/ProjectManager/ProjectManager/WebContent/DB/profiles/profile_Default.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Profile KeyId="" Name="" xmlns:tns="http://www.example.org/Profile" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Profile ../../projects/model/Profile.xsd ">
	<tns:Resources>
    <tns:resource>
      <tns:Credentials>
        <tns:rights>CREATE</tns:rights>
        <tns:rights>READ</tns:rights>
        <tns:rights>UPDATE</tns:rights>
        <tns:rights>DELETE</tns:rights>
      </tns:Credentials>      
      <tns:Path>Default.jsp</tns:Path>
      <tns:Description>Anonymous View</tns:Description>
    </tns:resource>
    <tns:resource>
      <tns:Credentials>
        <tns:rights>CREATE</tns:rights>
        <tns:rights>READ</tns:rights>
        <tns:rights>UPDATE</tns:rights>
        <tns:rights>DELETE</tns:rights>
      </tns:Credentials>      
      <tns:Path>help/help.jsp</tns:Path>
      <tns:Description>Help Page</tns:Description>
    </tns:resource>
  </tns:Resources>
  <tns:Description>Anonymous setup</tns:Description>
</tns:Profile>

=== zorglub01/ProjectManager/ProjectManager/src/com/services/projects/model/user_Default.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:User KeyId="Default" login="Default" xmlns:tns="http://www.example.org/Profile"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/Profile Profile.xsd ">
	<tns:eMail><![CDATA[Default@mail.com]]></tns:eMail>
	<tns:password><![CDATA[MyPwd]]></tns:password>
	<tns:FirstName>Default</tns:FirstName>
	<tns:Profile KeyId="Default" Name="Default">
		<tns:Resources>
			<tns:resource>
				<tns:Credentials>
					<tns:rights>CREATE</tns:rights>
				</tns:Credentials>
				<tns:Path>tns:Path</tns:Path>
				<tns:Description>tns:Description</tns:Description></tns:resource>
		</tns:Resources>
		<tns:Description>tns:Description</tns:Description>
	</tns:Profile></tns:User>
